folio-org/mod-workflow

Dockerfile, components/pom.xml, pom.xml, service/pom.xml
The Dockerfile uses
`FROM openjdk:11-jre-slim`
as base image. Run apt-get upgrade to upgrade vulnerable packages. This will fix these vulnerabilities:
* zlib/zlib1g Out-of-bounds Write https://nvd.nist.gov/vuln/detail/CVE-2022-37434
* gnutls28/libgnutls30 Double Free https://nvd.nist.gov/vuln/detail/CVE-2022-2509
=> FOLIO-3564: openjdk image: apt-get upgrade

components/pom.xml, pom.xml, service/pom.xml
After the release of 1.1.4 master must be a SNAPSHOT version.
=> Bump version of master branch from 1.1.4 to 1.1.5-SNAPSHOT

service/src/main/java/org/folio/rest/workflow/exception/WorkflowEngineServiceException.java, service/src/main/java/org/folio/rest/workflow/service/WorkflowEngineService.java
Catch the errors so that they can reported more properly. This returns the actual error message in the response so that the actual error messages reported by Camunda appear in the response when using say `fw-cli activate`.
The original errors are still reported in the log and the error is passed to the exceptions service.
This change results in a response such as this:
```
failed put http://127.0.0.1:9001/workflows/9908e4c0-6c48-4b2f-a487-a0398f74549f/activate {}
{
errors: [
{
message: `Failed to activate workflow: 403 Forbidden: "Access for user 'diku_admin' (aa572e0c-ca18-5024-8a78-9e1aaabffc5a) requires permission: camunda.workflow-engine.workflows.activate"!`,
type: 'WorkflowEngineServiceException',
code: '500 INTERNAL_SERVER_ERROR',
parameters: []
}
],
total_records: 1
}
```
=> Improve handling of errors when communicating with Camunda.

components/src/main/java/org/folio/rest/workflow/model/EmbeddedVariable.java
Resolves [MODWRKFLOW-12](https://issues.folio.org/browse/MODWRKFLOW-12)
Any existing databases will require an upgrade following this change.
A possibly way to quickly test if H2 is not working because of a problem like this may be to look into using `SET NON_KEYWORDS` in H2.
see: https://h2database.com/html/advanced.html#keywords
see: http://h2database.com/html/commands.html#set_non_keywords
=> MODWRKFLOW-12: Refactor column name from 'key' to 'vkey' for EmbeddedVariable.

service/pom.xml
These changes got lost during massive changes from spring boot 2 to spring boot 3.
This is currently restoring the old paths.
Once merged, I may end up having to get the files to appear at the top directory of the project rather than on the service directory.
=> Restore module descriptor generation.

service/pom.xml
This is a short term solution that places relative paths. A more robust design is preferred and ideally should be implemented in the future to replace this approach.
=> Modify pom files to ensure that the Descriptors get copied to the project top-level target directory.

service/descriptors/DeploymentDescriptor-template.json, service/descriptors/ModuleDescriptor-template.json, service/pom.xml, service/src/main/resources/changelog/changelog-master.xml
Deployment is not working as expected.
The upgrade to spring boot 3 and the addition of `folio-spring-support` has resulted in deployment regressions.
1. The resource variables syntax changed from say `${project.version}` into `@project.version@`.
2. A `changelog-master.xml` is now required due to Liquibase and `folio-spring-support` making that file be required (even if effectively empty).
This also removes some unused configuration, such as the resource exclusion for descriptors under `src/main/resources` (the descriptors are no longer stored there).
see: https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.properties-and-configuration
see: https://github.com/folio-org/folio-spring-support/blob/9f3042f4c0b5a27071793bf0904a68de1b6acddd/folio-spring-base/src/main …
=> Deployment fixes

service/pom.xml, service/src/main/resources/application.yaml, service/src/main/resources/openapi.yaml, service/src/test/resources/application.yaml
There is one unresolved issue relating to H2 and that has been commented out in the pom with an appropriate "FIXME" line.
The `folio-spring-support` introduces additional processing that inteferes with the processing by `mod-workflow`.
These can be found here:
- https://github.com/search?q=repo%3Afolio-org%2Ffolio-spring-support%20ConditionalOnProperty&type=code .
Of particular note are the `folio.tenant.validation` and the `header.validation.x-okapi-tenant.exclude.base-paths`.
Explicitly setting these in the `pom.xml` gets past several of these problems and allows for the `openapi.yaml` to be properly generated.
The `openapi.yaml` is still not being generated because the parent `pom.xml` has the `skip` configuration set to `true` for several of the required plugins.
Add the missing …
=> Fix problems relating to the pom, the application.yaml, and openapi.yaml generation.

service/src/main/resources/application.yaml
Without this setting, it attempts to access `classpath:/db/changelog/changelog-master.xml`. That path does not exist.
The path `classpath:/changelog/changelog-master.xml` does exist and so use that.
Once done deployment works.
This can also be set via the environment variable name `SPRING_LIQUIBASE_CHANGELOG`.
=> Setup default liquibase setting path that works.

README.md, docs/README.md, docs/fwz/README.md
This resolves [MODWRKFLOW-22](https://folio-org.atlassian.net/browse/MODWRKFLOW-22).
This documents the **FWZ** by documenting the format as seen in the fw-registry project.
There are some parts of the code that the documentation is omitted due to not enough information or the use case is unclear. One such example is the `workflow` property for the `DirectoryTask`.
This is the initial documentation.
There may be additional changes, clarifications, or improvements once the work begins on the MODWRKFLOW-21 issue.
The main `README.md` now links to the **FWZ** documentation.
The main `README.md` file was found lacking and now has something more than just `Introduction ...`.
An intermediate `README.md` is added under the `docs/` directory to help navigate between different documentation groups …
=> MODWRKFLOW-22: Document the FWZ format.

service/descriptors/ModuleDescriptor-template.json, service/src/main/resources/application.yaml
Expose additional notable environment variables in the Module Descriptor. The default settings provided, except for maybe the admin account name and associated passwords, should represent the sane default values for auto-deployment.
The ActiveMQ may be removed in the future but for now it is in use. Expose the settings such that if a non-local ActiveMQ is used, then it can be appropriately configured.
The Camunda information is now exposed.
The server port should not change from 8081 during deployment without additional module descriptor changes. Document the server port setting as a practice.
The server context path is also exposed as a practice.
The Flyway should be disabled by default for auto-deployment (in general).
Expose the tenant information to make the required changes more …
=> Improve Module Descriptor and application.yml to favor auto-deployment.

service/descriptors/ModuleDescriptor-template.json
[MODWRKFLOW-27](https://folio-org.atlassian.net/browse/MODWRKFLOW-27)
I overlooked updating the module descriptor and this is required.
=> MODWRKFLOW-27: Add missing module descriptor settings for FWZ import end point.

components/pom.xml, pom.xml, service/descriptors/ModuleDescriptor-template.json, service/pom.xml
This is a follow up to #104.
This adds the ActiveMQ port to the Deployment Descriptor.
Additional work may yet be needed to get ActiveMQ fully working across docker containers in the Scratch environment.
This also fixes the problem with "Workflow Parent".
This changes the name of the module and sub-modules/sub-projects (Components, and Service) to follow the same pattern as `mod-camunda` and all of the other Folio OKAPI modules.
The use of `workflow-parent` is no more and now it should show up as `mod-workflow`.
This change should hopefully help contribute to a well working FOLIO Scratch environment.
With this change, I am expecting the `mod-workflow` Dockerhub to now show up correctly.
see: https://hub.docker.com/r/folioci/workflow-parent
see: …
=> Deployment improvements

service/descriptors/ModuleDescriptor-template.json, service/src/main/java/org/folio/rest/workflow/controller/WorkflowController.java
[MODWRKFLOW-28](https://folio-org.atlassian.net/browse/MODWRKFLOW-28)
Sort the end points alphabetically so that I can more easily scan the files and find mistakes.
There appears to be configuration for the Spring Data Rest end points (which may or may not be made available in the future).
There are not end points for the explicit ones, such as `/workflows/{id}/delete`. The explicit end point for deleting a workflow is now exposed via the module descriptor.
The `/workflows/{id}/start` end point is also missing and is now exposed via the module descriptor. The permission is assigned to the `workflow.workflows.item.startTrigger`. There may or may not be a need to have a separate permission called `workflow.workflows.item.start`. Such a permissions change is considered out of scope.
=> MODWRKFLOW-28: Add missing or fix incorrect module descriptor end points.

service/src/main/java/org/folio/rest/workflow/controller/WorkflowController.java, service/src/main/java/org/folio/rest/workflow/exception/WorkflowNotFoundException.java, service/src/main/java/org/folio/rest/workflow/service/WorkflowEngineService.java, service/src/test/java/org/folio/rest/workflow/controller/WorkflowControllerTest.java, service/src/test/java/org/folio/rest/workflow/service/WorkflowEngineServiceTest.java
[MODWRKFLOW-28](https://folio-org.atlassian.net/browse/MODWRKFLOW-28)
The JPA delete entity is documented to fail silently when there is no entity found.
The existence check must be manually perfored to guarantee that a 404 Not Found happens.
The `delete` and `deactivate` share the same code so move the existence check into its own function.
Add appropriate unit tests.
Update existing unit tests.
Remove no longer needed unit tests.
=> MODWRKFLOW-28: Handle not found on delete.

pom.xml
This can be tested by doing the following (using firefox as an example web browser):
```shell
mvn clean test jacoco:report
firefox components/target/site/jacoco/index.html
firefox service/target/site/jacoco/index.html
```
=> Add support for Jacoco to allow for local coverage reports.

service/src/main/java/org/folio/rest/workflow/controller/ActionController.java, service/src/main/java/org/folio/rest/workflow/controller/EventController.java, service/src/main/java/org/folio/rest/workflow/controller/WorkflowController.java, service/src/main/resources/openapi.yaml
Resolves [MODWRKFLOW-14](https://folio-org.atlassian.net/browse/MODWRKFLOW-14).
These extra paths with a trailing forward-slash `/` (U+002F) should not longer be needed.
The `openapi.xml` file is rebuilt using `mvn clean verify -P openapi`.
There should no longer be any controller endpoints with explicit trailing slashes defined.
=> MODWRKFLOW-14: Clean up trailing slash work-around.

service/src/main/java/org/folio/rest/workflow/controller/WorkflowController.java, service/src/main/java/org/folio/rest/workflow/service/WorkflowEngineService.java
Resolves [MODWRKFLOW-42](https://folio-org.atlassian.net/browse/MODWRKFLOW-42).
The `deactivate` controller end point already has this check.
This adds the same check to the `activate` controller end point.
Also fix a mistake in the grammar of the `exists()` function documentation.
=> MODWRKFLOW-42: If Workflow is not found, Invalid Token message is incorrectly printed.

Dockerfile, components/.gitignore, components/src/main/java/org/folio/rest/workflow/model/Node.java, components/src/main/java/org/folio/rest/workflow/model/NodeInterface.java, components/src/main/java/org/folio/rest/workflow/model/converter/AbstractConverter.java, components/src/main/java/org/folio/rest/workflow/model/resolver/DeserializeAsJsonResolver.java, components/src/test/java/org/folio/rest/workflow/model/resolver/DeserializeAsJsonResolverTest.java, service/pom.xml, service/src/main/java/org/folio/rest/workflow/controller/EventController.java, service/src/main/resources/openapi.yaml, service/src/test/resources/application.yaml
Resolves [MODWRKFLOW-43](https://folio-org.atlassian.net/browse/MODWRKFLOW-43)
This also resolves [MODWRKFLOW-44](https://folio-org.atlassian.net/browse/MODWRKFLOW-44) given that the version is already being bumped to the 8.2.x versions.
Switch to JDK21 which has better spring-boot 3.3.x support.
The `folio-spring-base` now must be an 8.2.x version, such as `8.2.1`, or tests will fail (and probably runtime too).
Change the default `springframework.test` setting.
Using a builder is now the expected way to initialize the ObjectMapper.
Relocate the `JsonTypeInfo` and `JsonSubTypes` into a separate interface.
This appears to reduce problems following the upgrade to `3.3.7`.
The `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` must be disabled.
The following error is received:
```
Could not …
```
=> MODWRKFLOW-43: Upgrade to spring-boot 3.3.7 and folio-spring-base to 8.2.2.

service/pom.xml
Resolves [MODWRKFLOW-47](https://folio-org.atlassian.net/browse/MODWRKFLOW-47).
I first attempted upgrading to `1.27.1` and the following errors were observed during the unit tests:
```
[ERROR] Errors:
[ERROR]   WorkflowImportServiceTest.importFileWorksForBzip2AsBz2Test:264 » NoSuchMethod 'org.apache.commons.io.input.BoundedInputStream$Builder org.apache.commons.io.input.BoundedInputStream.builder()'
[ERROR]   WorkflowImportServiceTest.importFileWorksForBzip2Test:257 » NoSuchMethod 'org.apache.commons.io.input.BoundedInputStream$Builder org.apache.commons.io.input.BoundedInputStream.builder()'
[ERROR]   WorkflowImportServiceTest.importFileWorksForGzipAsGzTest:278 » NoSuchMethod 'org.apache.commons.io.input.BoundedInputStream$Builder …
```
=> MODWRKFLOW-47: Upgrade commons-compress to 1.26.2.

service/pom.xml, service/src/main/java/org/folio/rest/workflow/config/FolioSpringLiquibaseConfig.java, service/src/main/resources/application.yaml, service/src/test/java/org/folio/rest/workflow/controller/ActionControllerTest.java, service/src/test/java/org/folio/rest/workflow/controller/EventControllerTest.java, service/src/test/java/org/folio/rest/workflow/controller/WorkflowControllerTest.java, service/src/test/java/org/folio/rest/workflow/kafka/EventProducerTest.java, service/src/test/java/org/folio/rest/workflow/service/OkapiDiscoveryServiceWithDefaultPropertiesTest.java, service/src/test/java/org/folio/rest/workflow/service/WorkflowCqlServiceTest.java, service/src/test/java/org/folio/rest/workflow/service/WorkflowImportServiceTest.java, service/src/test/resources/application.yaml
Resolves [MODWRKFLOW-46](https://folio-org.atlassian.net/browse/MODWRKFLOW-46).
The `ObjectMapper` bean is provided because the `@MockitoSpyBean` no longer instantiates when there is no bean found in the way that no available or deprecated `@SpyBean` does.
Appease this error:
```
Description:
Parameter 2 of constructor in org.folio.spring.service.TenantService required a bean of type 'org.folio.spring.liquibase.FolioSpringLiquibase' that could not be found.
Action:
Consider defining a bean of type 'org.folio.spring.liquibase.FolioSpringLiquibase' in your configuration.
```
Switch `folio-spring-support` dependency to `8.3.0-SNAPSHOT` because this is needed for the Spring Boot 3.4 support. Prior versions do not work under Spring-Boot 3.4.
Update the Controlling Access to Actuator Endpoints …
=> MODWRKFLOW-46: Make compatible with spring-boot 3.4 upgrades.
